psevdo ol
gudzsv/project-syntax-samurais-01 pull request #16
Opened 2024-01-11 21:39 UTC by INNA-KUSHNIRR1

2024-01-11 22:38 UTC, gudzsv commented on src/partials/courses.html
> +<section id="courses" class="courses">
Додай додатковий клас для відступу вгорі секції спільний для всіх  `section-mt`

2024-01-11 22:41 UTC, gudzsv requested changes
Додай додатковий клас для відступу вгорі секції спільний для всіх `section-mt`
чекаю на новий коміт від тебе. дякую

2024-01-12 09:43 UTC, INNA-KUSHNIRR1 commented
привет. что-то я не пойму как внести изменения. я у себя в десктопе ветку удалила. видимо поспешила. Я могу как-то отсюда её скачать. пипец. гитхаб пока ещё это моя боль((((

2024-01-12 10:01 UTC, gudzsv reviewed
good

2024-01-12 10:02 UTC, gudzsv approved these changes
good job

2024-01-12 10:04 UTC, merged